-- ============================================================================
-- Datibot · Embudos — esquema Supabase (modelo NÚMERO vs PRODUCTO)
-- Ejecuta este SQL UNA vez en el SQL editor de Supabase del proyecto de embudos.
-- La app "Embudos" de Datibot solo lee/escribe estas filas; el motor de n8n las
-- lee en vivo. Es idempotente (IF NOT EXISTS): puedes correrlo sin miedo.
--
-- Nota (asunción de modelado): `productos` va por (producto, pais) — una fila por
-- país, igual que el antiguo config_bots pero SIN los campos técnicos del número
-- (esos viven en `numeros`). Los mensajes/prompts suelen ser iguales entre países
-- (la app los escribe en las 5 filas); los datos de pago cambian por país.
-- ============================================================================

-- 1) NÚMEROS — lo ESTÁTICO de cada número de WhatsApp (una fila por número).
create table if not exists public.numeros (
  phone_id         text primary key,            -- phone_number_id de Meta
  nombre           text,                         -- nombre para identificar la cuenta publicitaria
  numero_whatsapp  text not null,               -- número marcable, ej. 573227784838
  waba_id          text,                        -- WhatsApp Business Account id
  capi_token       text,                        -- token System User (CAPI / envíos)  [SENSIBLE]
  account_id       text,                        -- id de cuenta de Chatwoot
  credencial_wa    text,                        -- referencia a la credencial de WA en n8n
  pais             text,                        -- país que atiende (CO/PE/EC/CL/VE)
  producto_activo  text,                        -- ⭐ apuntador: qué producto vende HOY
  actualizado_at   timestamptz default now()
);
-- Si la tabla `numeros` YA existe (no es la primera vez), corre solo esto para el
-- nombre de la cuenta publicitaria:
--   alter table public.numeros add column if not exists nombre text;

-- 2) PRODUCTOS — lo VARIABLE por producto + país (reemplaza el negocio de config_bots).
create table if not exists public.productos (
  producto                text not null,
  pais                    text not null,        -- CO/PE/EC/CL/VE
  pixel_id                text,                 -- el pixel es del producto/campaña
  page_id                 text,
  -- Mensajes fijos
  msg_bienvenida          text,
  msg_cobro               text,
  msg_bonos_intro         text,
  msg_datos_pago          text,
  msg_felicitacion        text,
  -- Prompts de las IAs
  system_prompt_convencer text,
  system_prompt_cobrar    text,
  -- Datos de pago (por país)
  titular_cuenta          text,
  numero_cuenta           text,
  metodo_pago             text,
  metodos_pago_texto      text,
  brec_alias              text,
  moneda                  text,
  moneda_simbolo          text,
  precio_base             numeric,
  -- Validación del comprobante
  validacion_titular      text,
  validacion_cuenta_hint  text,
  validacion_alias        text,
  actualizado_at          timestamptz default now(),
  primary key (producto, pais)
);

-- 3) PASOS_EMBUDO — la secuencia del embudo como filas (el corazón).
create table if not exists public.pasos_embudo (
  id             bigint generated by default as identity primary key,
  producto       text not null,
  estado         text not null,   -- MENU | VIDEO | CONFIRMACION | ENTREGA | STOP
  orden          int  not null,
  tipo           text not null,   -- mensaje | video | pdf | boton | etiqueta | wait
  contenido      text,            -- según `fuente` (ver spec)
  fuente         text,            -- config | media | rotador | directo
  delay_segundos int  default 0,  -- espera DESPUÉS del paso (anti-baneo)
  unique (producto, estado, orden)
);

-- 4) MENSAJES_ROTADOR — variantes anti-spam (por producto, país-agnóstico).
create table if not exists public.mensajes_rotador (
  id       bigint generated by default as identity primary key,
  producto text not null,
  campo    text not null,   -- ej. menu, boton_texto
  variante int  not null,   -- 1,2,3...
  texto    text not null,
  unique (producto, campo, variante)
);

-- 5) MEDIA_BOTS — archivos precargados (por producto); guarda los media_id de WhatsApp.
create table if not exists public.media_bots (
  producto             text primary key,
  phone_id             text,       -- el número que subió la media (los media_id están atados a él)
  capi_token           text,       -- [SENSIBLE]
  url_video            text,
  video_media_id       text,
  video_caption        text,
  pdf_1_url text, pdf_1_media_id text, pdf_1_caption text, pdf_1_filename text,
  pdf_2_url text, pdf_2_media_id text, pdf_2_caption text, pdf_2_filename text,
  pdf_3_url text, pdf_3_media_id text, pdf_3_caption text, pdf_3_filename text,
  pdf_4_url text, pdf_4_media_id text, pdf_4_caption text, pdf_4_filename text,
  pdf_5_url text, pdf_5_media_id text, pdf_5_caption text, pdf_5_filename text,
  pdf_6_url text, pdf_6_media_id text, pdf_6_caption text, pdf_6_filename text,
  media_actualizado_at timestamptz default now()
);

-- ----------------------------------------------------------------------------
-- SEGURIDAD (recomendado): estas tablas guardan tokens (capi_token). La app y el
-- motor de n8n usan la SERVICE KEY (rol service_role), que SALTA el RLS. Activa RLS
-- para que la anon key NO pueda leer/escribir si alguna vez se expone. Deja esto
-- comentado si tu motor de n8n usa la anon key (no debería). Descoméntalo si ambos
-- (app y motor) usan la service key:
--
-- alter table public.numeros          enable row level security;
-- alter table public.productos        enable row level security;
-- alter table public.pasos_embudo     enable row level security;
-- alter table public.mensajes_rotador enable row level security;
-- alter table public.media_bots       enable row level security;
